### ISSUE TITLE
[Bug]: can not deploy qwen2.5 with vllm

### ISSUE THREAD

**Issue by joyyyhuang** [QwenLM/Qwen2.5#1048]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-7B-Instruct

### What is the scenario where the problem happened?

deployment with vllm

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

OS: Centos
Python: 3.10
GPUs: NVIDIA L20
NVIDIA driver: 535
CUDA compiler: 12.1 
PyTorch: 2.5.1+cu121

### Log output

```shell
INFO 11-01 18:37:07 model_runner.py:1056] Starting to load model model/Qwen2.5-7B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  1.79it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.43it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.44it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.42it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.45it/s]

INFO 11-01 18:37:11 model_runner.py:1067] Loading model weights took 14.2487 GB
INFO 11-01 18:37:14 worker.py:260] Memory profiling results: total_gpu_memory=95.00GiB initial_memory_usage=18.93GiB peak_torch_memory=18.62GiB memory_usage_post_profile=19.03Gib non_torch_memory=4.75GiB kv_cache_size=62.13GiB gpu_memory_utilization=0.90
INFO 11-01 18:37:15 gpu_executor.py:122] # GPU blocks: 72714, # CPU blocks: 4681
INFO 11-01 18:37:15 gpu_executor.py:126] Maximum concurrency for 32768 tokens per request: 35.50x
INFO 11-01 18:37:17 model_runner.py:1395] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 11-01 18:37:17 model_runner.py:1399] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
Traceback (most recent call last):
  File "/root/miniconda3/envs/py310/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/root/vllm/vllm/scripts.py", line 195, in main
    args.dispatch_function(args)
  File "/root/vllm/vllm/scripts.py", line 41, in serve
    uvloop.run(run_server(args))
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/root/vllm/vllm/entrypoints/openai/api_server.py", line 575, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/root/miniconda3/envs/py310/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/vllm/vllm/entrypoints/openai/api_server.py", line 107, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/root/miniconda3/envs/py310/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/root/vllm/vllm/entrypoints/openai/api_server.py", line 197, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start
```

### Description

step 1: I install vllm from source code
step 2: Use local model `vllm serve model/Qwen2.5-7B-Instruct`
step 3: The error come!!!

**Comment by joyyyhuang** [comment]
I solve this problem by another envs.
python=3.12,7 torch=2.5.0+cu12.4, then use
`pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl`
install the latest version of vllm.
