### ISSUE TITLE
[Bug]: AttributeError: Model Qwen2ForCausalLM does not support BitsAndBytes quantization yet.

### ISSUE THREAD

**Issue by yananchen1989** [QwenLM/Qwen2.5#1049]
### Model Series

Qwen2.5

### What are the models used?

Qwen/Qwen2.5-1.5B-Instruct

### What is the scenario where the problem happened?

[inference with] with [vllm]

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

vllm                              0.6.3.post1
vllm-flash-attn                   2.6.1

### Log output

```shell
INFO 11-01 16:29:09 model_runner.py:1056] Starting to load model Qwen/Qwen2.5-0.5B-Instruct...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/moa/ttt.py", line 11, in <module>
[rank0]:     llm = LLM(model= args.llm_name, dtype='half', max_model_len= 2048, 
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 40, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py", line 183, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1148, in load_model
[rank0]:     self._load_weights(model_config, model)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1033, in _load_weights
[rank0]:     raise AttributeError(
[rank0]: AttributeError: Model Qwen2ForCausalLM does not support BitsAndBytes quantization yet.
```

### Description

code:
```python
llm = LLM(model= args.llm_name, dtype='half', max_model_len= 2048, 
            tensor_parallel_size=torch.cuda.device_count(), gpu_memory_utilization= 0.3, #seed=None,
            trust_remote_code=True,
            quantization="bitsandbytes", load_format="bitsandbytes", enforce_eager=True, 
            enable_lora=False,
            cpu_offload_gb = 48
            #tokenizer_mode= "mistral" if args.llm_name.startswith('mistralai') else 'auto'
        )
```

请问目前qwen 在vllm中，不能使用量化吗？
有没有什么别的方法可以降低cuda memory呢？

**Comment by jklj077** [comment]
https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html#serving-quantized-models

**Comment by jklj077** [comment]
`vllm>=0.6.4` now supports bnb for Qwen models (https://github.com/vllm-project/vllm/pull/9467), but please be aware that bnb in general leads to greater accuracy loss. it is recommened to use AWQ or GPTQ or GGUF with imatrix models.

**Comment by ysahil97** [comment]
Thanks @jklj077 for listing this version. Even I was facing the same issue, and it's now working for me for Qwen1.5
