### ISSUE TITLE
[Bug]: 使用Qwen2.5-72B-Instruct-AWQ和Qwen2.5-32B-Instruct-AWQ官方给的演示例子，运行的时候提示：returned non-zero exit status 1

### ISSUE THREAD

**Issue by SuSuStarSmile** [QwenLM/Qwen2.5#1059]
### Model Series

Qwen2.5

### What are the models used?

Qwen2.5-72B-Instruct-AWQ和Qwen2.5-32B-Instruct-AWQ

### What is the scenario where the problem happened?

 inference with transformers

### Is this a known issue?

- [X] I have followed [the GitHub README](https://github.com/QwenLM/Qwen2.5).
- [X] I have checked [the Qwen documentation](https://qwen.readthedocs.io) and cannot find an answer there.
- [X] I have checked the documentation of the related framework and cannot find useful information.
- [X] I have searched [the issues](https://github.com/QwenLM/Qwen2.5/issues?q=is%3Aissue) and there is not a similar one.

### Information about environment

操作系统：CentOS Linux release 7.9.2009 (Core)
python：3.10
GPU:4*V100
NVIDIA driver：535.183.06
CUDA Version: 12.2  
PyTorch:2.3.0+cu121

Python packages
Package                  Version     Editable project location
------------------------ ----------- -------------------------------------
accelerate               1.1.1
aiohappyeyeballs         2.4.3
aiohttp                  3.10.10
aiosignal                1.3.1
async-timeout            4.0.3
attrs                    24.2.0
autoawq                  0.2.6+cu121 
certifi                  2024.8.30
charset-normalizer       3.4.0
datasets                 3.1.0
dill                     0.3.8
filelock                 3.16.1
frozenlist               1.5.0
fsspec                   2024.9.0
huggingface-hub          0.26.2
idna                     3.10
Jinja2                   3.1.4
MarkupSafe               3.0.2
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.4.2
numpy                    2.1.3
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.77
nvidia-nvtx-cu12         12.1.105
packaging                24.1
pandas                   2.2.3
pillow                   11.0.0
pip                      24.3.1
propcache                0.2.0
psutil                   6.1.0
pyarrow                  18.0.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
safetensors              0.4.5
setuptools               75.3.0
six                      1.16.0
sympy                    1.13.3
tokenizers               0.20.3
torch                    2.3.0
torchvision              0.18.0
tqdm                     4.67.0
transformers             4.46.2
triton                   2.3.0
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.44.0
xxhash                   3.5.0
yarl                     1.17.1
zstandard                0.23.0

### Log output

```shell
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 11/11 [00:36<00:00,  3.28s/it]
/tmp/tmp1b0sks7u/main.c: In function ‘list_to_cuuint64_array’:
/tmp/tmp1b0sks7u/main.c:354:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
/tmp/tmp1b0sks7u/main.c:354:3: note: use option -std=c99 or -std=gnu99 to compile your code
/tmp/tmp1b0sks7u/main.c: In function ‘list_to_cuuint32_array’:
/tmp/tmp1b0sks7u/main.c:365:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (Py_ssize_t i = 0; i < len; i++) {
   ^
Traceback (most recent call last):
  File "/home/sxw/2-Project/4-demo/Qwen2.5-32B-Instruct-AWQ-backup.py", line 76, in <module>
    generated_ids = model.generate(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1164, in forward
    outputs = self.model(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 895, in forward
    layer_outputs = decoder_layer(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 623, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 501, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/sxw/2-Project/5-AutoAWQ/AutoAWQ/awq/modules/linear/gemm.py", line 271, in forward
    out = WQLinearMMFunction.apply(
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/sxw/2-Project/5-AutoAWQ/AutoAWQ/awq/modules/linear/gemm.py", line 63, in forward
    out = awq_dequantize_triton(qweight, scales, qzeros)
  File "/home/sxw/2-Project/5-AutoAWQ/AutoAWQ/awq/modules/triton/gemm.py", line 283, in awq_dequantize_triton
    awq_dequantize_kernel[grid](
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/jit.py", line 167, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/jit.py", line 363, in run
    device = driver.get_current_device()
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/driver.py", line 209, in __getattr__
    self._initialize_obj()
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/driver.py", line 206, in _initialize_obj
    self._obj = self._init_fn()
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/driver.py", line 239, in initialize_driver
    return CudaDriver()
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/driver.py", line 102, in __init__
    self.utils = CudaUtils()
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/runtime/driver.py", line 49, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/common/build.py", line 106, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp1b0sks7u/main.c', '-O3', '-I/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/include/python3.10', '-I/tmp/tmp1b0sks7u', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp1b0sks7u/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.
```

#### 在从huggingface下载Qwen2.5-72B-Instruct-AWQ和Qwen2.5-32B-Instruct-AWQ模型后，使用huggingface上面官方给的演示例子，运行代码的时候提示：
raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmp1b0sks7u/main.c', '-O3', '-I/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/lib/python3.10/site-packages/triton/common/../third_party/cuda/include', '-I/home/sxw/1-Evn/1-miniconda3/envs/autoAWQ/include/python3.10', '-I/tmp/tmp1b0sks7u', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmp1b0sks7u/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-L/lib64', '-L/lib', '-L/lib64', '-L/lib']' returned non-zero exit status 1.

#### 使用的模型
1. Qwen2.5-72B-Instruct-AWQ
2. Qwen2.5-32B-Instruct-AWQ

**Comment by jklj077** [comment]
the `pip list` shows `torch 2.3.0` and `autoawq 0.2.6+cu121` but no CUDA kernels installed. it means `triton` is used to build the CUDA kernels, and you will need CUDA build tools (the error suggests that you have an incompatible C or C++ compiler. you have an incompatible CUDA compiler as well.). Please try also installing `autoawq-kernels` with `pip install autoawq-kernels`.
