### ISSUE TITLE
如何使用VLLM离线推理，支持长文本输入

### ISSUE THREAD

**Issue by mars-ch** [QwenLM/Qwen2.5#844]
按照model card的界面修改了config.json，还有其他地方需要修改吗？
不需要的话这里报错：
```
--- Logging error ---
Traceback (most recent call last):
  File "/miniforge/envs/iris/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/miniforge/envs/iris/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/vllm/logging/formatter.py", line 11, in format
    msg = logging.Formatter.format(self, record)
  File "/miniforge/envs/iris/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/miniforge/envs/iris/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "**", line 116, in <module>
    process(**)
  File "**", line 68, in process
    llm = LLM(model="**", tensor_parallel_size = 4, enforce_eager = True)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 155, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 438, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/miniforge/envs/iris/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 802, in create_engine_config
    scheduler_config = SchedulerConfig(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/vllm/config.py", line 815, in __init__
    logger.info(
Message: 'Chunked prefill is enabled with max_num_batched_tokens=%d.'
Arguments: (None,)
```

**Comment by jklj077** [comment]
Hi, 

how did you start the vllm service? it appears that you have enabled chunked prefill. if so, there is a bug at vllm 0.5.3. you can try upgrading to vllm 0.5.3.post1 or 0.5.4.

**Comment by mars-ch** [comment]
I used
```
 from vllm import LLM

 llm = LLM(model="**", tensor_parallel_size = 4, enforce_eager = True)
```
 to start the service
 
 I will have a try with 0.5.3.post1

**Comment by mars-ch** [comment]
There are still some problems.

`Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.`

**Comment by jklj077** [comment]
please refer to https://www.github.com/vllm-project/vllm/issues/2729 to disable chunked prefill if you are using non-Ampere cards.
