### ISSUE TITLE
[AutoAWQ] 请问微调并且量化后的Qwen2模型能否在CPU上运行呢？

### ISSUE THREAD

**Issue by Autism-al** [QwenLM/Qwen2.5#898]
将设备改为cpu后报错。
Traceback (most recent call last):
  File "/home/lmf/llm/Qwen1.5-4B-finetuning-accelerate/Q4B_sft_test.py", line 74, in <module>
    get_answer('data/mutiple_task_test.json')
  File "/home/lmf/llm/Qwen1.5-4B-finetuning-accelerate/Q4B_sft_test.py", line 57, in get_answer
    generated_ids = model.generate(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1104, in forward
    outputs = self.model(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 915, in forward
    layer_outputs = decoder_layer(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 655, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 542, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lmf/llm/Qwen1.5-4B-finetuning-accelerate/AutoAWQ/awq/modules/linear/gemm.py", line 243, in forward
    out = WQLinearMMFunction.apply(
  File "/home/lmf/anaconda3/envs/qwenvllm/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lmf/llm/Qwen1.5-4B-finetuning-accelerate/AutoAWQ/awq/modules/linear/gemm.py", line 47, in forward
    out = awq_ext.gemm_forward_cuda(
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/usr/share/miniconda3/envs/build/lib/python3.10/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":28, please report a bug to PyTorch.

**Comment by jklj077** [comment]
Hi, 

You should be able to run AutoAWQ with CPU since v0.2.6. Please refer to its documentation: https://casper-hansen.github.io/AutoAWQ/#installation-notes
